spring:
  application:
    name: user-service   
management:
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint:
        http://localhost:9411/api/v2/spans
        
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
