spring:
  application:
    name: USER
  boot:
   admin:
     client:
       url:
        - http://localhost:8081 
  main:
    allow-circular-references: true    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
      
  endpoint:
    health:
      show-details: always
          
resilience4j:
  circuitbreaker:
    instances: 
     ratingHotelBreaker  :
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
